# Generated by Django 4.2.3 on 2023-07-22 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license', models.CharField(max_length=200, unique=True)),
                ('license_issued_date', models.DateTimeField(verbose_name='issued date')),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 697181, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('machine_id', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 711096, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(max_length=200)),
                ('vehicle_plate', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 706593, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
                ('trip_no', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 697181, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(default='normal', max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 711096, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTypes',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 14, 46, 57, 711096))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_types',
            },
        ),
        migrations.CreateModel(
            name='Subcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcity_name', models.CharField(max_length=200)),
                ('number_of_stations', models.PositiveIntegerField()),
                ('number_of_machines', models.PositiveIntegerField()),
                ('number_of_routes', models.PositiveIntegerField()),
                ('number_of_vehicles', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 697181, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=200)),
                ('plate_no', models.CharField(max_length=200, unique=True)),
                ('model', models.CharField(max_length=200)),
                ('vehicle_size', models.PositiveSmallIntegerField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 703953, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.driver')),
                ('subcity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='evdcs.subcity')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_time', models.DateTimeField(verbose_name='coming time')),
                ('going_time', models.DateTimeField(verbose_name='going time')),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 711096, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.route')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclesLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 711096, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
                ('device_id', models.CharField(max_length=200)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('number_of_routes', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 708103, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
                ('subcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.subcity')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='evdcs.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='evdcs.station'),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=200, unique=True)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 710100, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.station')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.profile'),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounde', models.PositiveIntegerField()),
                ('route_type', models.CharField(max_length=20, null=True)),
                ('route_length', models.CharField(max_length=200, null=True)),
                ('route_price', models.FloatField(null=True)),
                ('source_name', models.CharField(max_length=200, null=True)),
                ('destination_name', models.CharField(max_length=200, null=True)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 711096, tzinfo=datetime.timezone.utc), verbose_name='date registered')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.route')),
                ('vehicle_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AssignVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('assign_date', models.DateTimeField(default=datetime.datetime(2023, 7, 22, 11, 46, 57, 711096, tzinfo=datetime.timezone.utc), verbose_name='date assigned')),
                ('status', models.CharField(default='pending', max_length=200)),
                ('vehicles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evdcs.vehicle')),
            ],
        ),
    ]
