# Generated by Django 4.2.3 on 2023-07-22 11:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evdcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignvehicle',
            name='assign_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date assigned'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='route',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='routetypes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 14, 48, 31, 710043)),
        ),
        migrations.AlterField(
            model_name='station',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='subcity',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='vehicleslocation',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='waitingtime',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
    ]
