# Generated by Django 4.2.3 on 2023-07-22 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evdcs', '0002_alter_assignvehicle_assign_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetypes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 15, 56, 49, 293128)),
        ),
    ]
